export class Method {
  static GetUserList = `/GetUserList`;
  static GetSupplierList = `/GetSupplierList`;
  static GetSupplierByGSTNumber = `/GetSupplierByGSTNumber`;
  static GetSupplierDetailsById = `/GetSupplierDetailsById`;
  static GetProductList = `/GetProductList`;
  static GetPlantList = `/GetPlantList`;
  static GetStateList = `/GetStateList`;
  static GetStateListByCountryCode = `/GetStateListByCountryCode`;
  static GetProductGroupList = `/GetProductGroupList`;
  static CreateSupplier = `/CreateSupplier`;
  static ApproveSupplier = `/ApproveSupplier`;
  static GetCountryList = `/GetCountryList`;
  static Login = `/login`;
  static GetStorageLocationByPlantCode = `/GetLocationListByPlantCode`;
  static GetAllUnitList = `/GetAllUnitList`;
  static GetDocTypeList = `/GetDocTypeList`;
  static CreatePurchaseRequisition = `/CreatePurchaseRequisition`;
  static GetAllPRHeaderList = `/GetAllPRHeaderList`;
  static GetPRDetailsById = `/GetPRDetailsById`;
}
