export interface Suppliers {
    Id: number;
    SupplierCode?: string,
    FirstName?: string;
    LastName?: string;
    AccountGroup?: string;
    ShortName?: string;
    GSTNumber?: string;
    GSTRegionCode?: string;
    PANNumber?: string;
    Street1?: string;
    Street2?: string;
    PostalCode?: string;
    City?: string;
    State?: string;
    Country?: string;
    Language?: string;
    Phone?: string;
    Email?: string;
    PurchaseOrg?: string;
    GSTVendorClass?: string;
    CompanyCode?: string;
    PayTermsCode?: string;
    Currency?: string;
    IsActive?: string;
    CreatedBy?: string;
    CreatedOn?: string;
    UpdatedBy?: string;
    UpdatedOn?: string;
    IsDeleted?: string;
    DeletedOn?: string;
    Extra1?: string;
    Extra2?: string;
}